services:

  sql-db:
    image: postgres
    restart: unless-stopped
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  # nosql-db:
  #   image: mongo
  #   restart: always
  #   # set shared memory limit when using docker compose
  #   shm_size: 128mb

  adminer: # provides a web interface to manage the database
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
